name: Fuzz Testing

on:
  pull_request:
    branches:
      - main  # Trigger for pull requests to the 'main' branch

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run fuzz.py
      run: |
        python MLForensics-farzana/FAME-ML/fuzz.py  # Run the fuzzing script
